services:
  - type: web
    name: master-yourself-ai-backend
    env: python
    buildCommand: |
      cd backend
      chmod +x build.sh
      ./build.sh
    startCommand: |
      cd backend
      ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
