"""Add regeneration_count to ai_challenges

Revision ID: 18337c7235c4
Revises: 534dd83c5d59
Create Date: 2025-08-29 10:15:11.634676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18337c7235c4'
down_revision = '534dd83c5d59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_ai_challenges')
    with op.batch_alter_table('ai_challenges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('regeneration_count', sa.Integer(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_challenges', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('regeneration_count')

    op.create_table('_alembic_tmp_ai_challenges',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('challenge_date', sa.DATE(), nullable=False),
    sa.Column('completed', sa.BOOLEAN(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('intensity', sa.INTEGER(), nullable=True),
    sa.Column('challenge_text', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
