"""Add start_date to long_term_goals

Revision ID: 4daf19764e9a
Revises: 
Create Date: 2025-08-18 19:38:46.343390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4daf19764e9a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('long_term_goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('long_term_goals', schema=None) as batch_op:
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###
