"""add_intensity_to_ai_challenges

Revision ID: 534dd83c5d59
Revises: 80912d32d6b6
Create Date: 2025-08-26 18:14:18.837442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '534dd83c5d59'
down_revision = '80912d32d6b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_challenges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intensity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_challenges', schema=None) as batch_op:
        batch_op.drop_column('intensity')

    # ### end Alembic commands ###
