"""Add archived field to long_term_goals

Revision ID: 8b6eb3a1e8c8
Revises: bac01e992175
Create Date: 2025-08-25 14:15:15.997364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b6eb3a1e8c8'
down_revision = 'bac01e992175'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('long_term_goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('long_term_goals', schema=None) as batch_op:
        batch_op.drop_column('archived')

    # ### end Alembic commands ###
