"""add_archived_field_to_weekly_goals

Revision ID: bac01e992175
Revises: 88737502b575
Create Date: 2025-08-25 12:02:52.075375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bac01e992175'
down_revision = '88737502b575'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_goals', schema=None) as batch_op:
        batch_op.drop_column('archived')

    # ### end Alembic commands ###
