// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmnQMphFTwEK8H_LMLRuvQXmkPGnjpayM',
    appId: '1:1004680248723:web:d43ebe5c2d927323d5fc66',
    messagingSenderId: '1004680248723',
    projectId: 'masteryourselfai-50d2c',
    authDomain: 'masteryourselfai-50d2c.firebaseapp.com',
    storageBucket: 'masteryourselfai-50d2c.firebasestorage.app',
    measurementId: 'G-LP2ZCM9YQN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcstQeICnVar_u9jIc-MNz_oDjV6DFZzw',
    appId: '1:1004680248723:android:6a85ed282cb3426dd5fc66',
    messagingSenderId: '1004680248723',
    projectId: 'masteryourselfai-50d2c',
    storageBucket: 'masteryourselfai-50d2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDU8vNUh1Lt0GQW1BiBM9PwasDQWFAfsI',
    appId: '1:1004680248723:ios:acc9a80031fd3360d5fc66',
    messagingSenderId: '1004680248723',
    projectId: 'masteryourselfai-50d2c',
    storageBucket: 'masteryourselfai-50d2c.firebasestorage.app',
    iosClientId: '1004680248723-963216jjv0kh1oskm911uis35q5sc8h2.apps.googleusercontent.com',
    iosBundleId: 'com.masteryourself.ai.masterYourselfAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDU8vNUh1Lt0GQW1BiBM9PwasDQWFAfsI',
    appId: '1:1004680248723:ios:acc9a80031fd3360d5fc66',
    messagingSenderId: '1004680248723',
    projectId: 'masteryourselfai-50d2c',
    storageBucket: 'masteryourselfai-50d2c.firebasestorage.app',
    iosClientId: '1004680248723-963216jjv0kh1oskm911uis35q5sc8h2.apps.googleusercontent.com',
    iosBundleId: 'com.masteryourself.ai.masterYourselfAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmnQMphFTwEK8H_LMLRuvQXmkPGnjpayM',
    appId: '1:1004680248723:web:86a026b2b41d2041d5fc66',
    messagingSenderId: '1004680248723',
    projectId: 'masteryourselfai-50d2c',
    authDomain: 'masteryourselfai-50d2c.firebaseapp.com',
    storageBucket: 'masteryourselfai-50d2c.firebasestorage.app',
    measurementId: 'G-V7BFXW91RK',
  );

}